@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

LAYOUT_LEFT_RIGHT()

' Aktor eksternal
Person(kasir, "Kasir", "Petugas yang mengoperasikan POS untuk melakukan penjualan")
Person(sistem_pembayaran, "Sistem Pembayaran", "Penyedia layanan pembayaran (misal: Midtrans, OVO, Gopay)")
System_Ext(laporan_akuntansi, "Sistem Laporan Akuntansi", "Sistem eksternal yang menerima data transaksi untuk pembukuan")

' Sistem POS
System_Boundary(pos_system, "Sistem POS") {
    System(pos, "Point of Sale", "Aplikasi POS", "Mengelola penjualan, inventori, produk, dan integrasi pembayaran")
}

' Relasi
Rel(kasir, pos, "Melakukan transaksi penjualan dan pengelolaan inventori")
Rel(pos, sistem_pembayaran, "Mengirim data pembayaran", "API HTTPS")
Rel(sistem_pembayaran, pos, "Konfirmasi status pembayaran", "Callback API")
Rel(pos, laporan_akuntansi, "Mengirim data transaksi untuk laporan")

@enduml
